/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#bc4800',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdbcd',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#574500',
        'primary-fixed': '#dbe1ff',
        'secondary-container': '#fed01b',
        'inverse-primary': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-background': '#0b1c30',
        'surface': '#f8f9ff',
        'surface-container': '#e5eeff',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#231b00',
        'secondary': '#735c00',
        'outline-variant': '#c3c6d7',
        'on-secondary-container': '#6f5900',
        'on-tertiary-container': '#ffede6',
        'primary-container': '#2563eb',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'secondary-fixed-dim': '#eec200',
        'on-tertiary-fixed-variant': '#7d2d00',
        'background': '#f8f9ff',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#434655',
        'tertiary-fixed-dim': '#ffb596',
        'error': '#ba1a1a',
        'primary': '#004ac6',
        'on-primary-container': '#eeefff',
        'error-container': '#ffdad6',
        'surface-container-low': '#eff4ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'on-error-container': '#93000a',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#0053db',
        'primary-fixed-dim': '#b4c5ff',
        'on-surface': '#0b1c30',
        'outline': '#737686',
        'on-tertiary-fixed': '#360f00',
        'surface-container-highest': '#d3e4fe',
        'secondary-fixed': '#ffe083',
        'tertiary': '#943700',
        'on-primary-fixed-variant': '#003ea8',
        'on-error': '#ffffff',
        'inverse-surface': '#213145',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'md': '16px',
        'lg': '24px',
        'base': '4px',
        'sm': '8px',
        '2xl': '48px',
        'xl': '32px',
        'gutter': '16px',
        'xs': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-status-mobile': ['36px', { lineHeight: '40px', fontWeight: '800' }],
        'headline-lg': ['30px', { lineHeight: '36px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-status': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 3s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.5s ease-out forwards',
      },
    },
  },
  plugins: [],
};
