/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Amber/Warm Brown Color Scheme
        'surface': '#fff8f5',
        'surface-dim': '#e0d8d5',
        'surface-bright': '#fff8f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf2ee',
        'surface-container': '#f4ece8',
        'surface-container-high': '#eee7e3',
        'surface-container-highest': '#e9e1dd',
        'on-surface': '#1e1b19',
        'on-surface-variant': '#554336',
        'inverse-surface': '#33302d',
        'inverse-on-surface': '#f7efeb',
        'outline': '#887364',
        'outline-variant': '#dbc2b0',
        'surface-tint': '#904d00',
        
        'primary': '#8d4b00',
        'on-primary': '#ffffff',
        'primary-container': '#b15f00',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb77d',
        'primary-fixed': '#ffdcc3',
        'primary-fixed-dim': '#ffb77d',
        'on-primary-fixed': '#2f1500',
        'on-primary-fixed-variant': '#6e3900',
        
        'secondary': '#895033',
        'on-secondary': '#ffffff',
        'secondary-container': '#feb28f',
        'on-secondary-container': '#794227',
        'secondary-fixed': '#ffdbcc',
        'secondary-fixed-dim': '#ffb694',
        'on-secondary-fixed': '#351000',
        'on-secondary-fixed-variant': '#6d391e',
        
        'tertiary': '#6e5e0d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bfab56',
        'on-tertiary-container': '#4b3f00',
        'tertiary-fixed': '#f9e287',
        'tertiary-fixed-dim': '#dcc66e',
        'on-tertiary-fixed': '#221b00',
        'on-tertiary-fixed-variant': '#534600',
        
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        
        'background': '#fff8f5',
        'on-background': '#1e1b19',
        'surface-variant': '#e9e1dd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'md': '16px',
        'lg': '24px',
        'base': '4px',
        'sm': '8px',
        '2xl': '48px',
        'xl': '32px',
        'gutter': '16px',
        'xs': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-status-mobile': ['36px', { lineHeight: '40px', fontWeight: '800' }],
        'headline-lg': ['30px', { lineHeight: '36px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-status': ['48px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 3s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.5s ease-out forwards',
      },
    },
  },
  plugins: [],
};
